import os
import oracledb
import pandas as pd

try:
    conn = oracledb.connect(user='RM565518', password="250806", dsn='oracle.fiap.com.br:1521/ORCL')
    inst_cadastro = conn.cursor()
    inst_consulta = conn.cursor()
    inst_exclusao = conn.cursor()
except Exception as e:
    print("Erro na conexão: ", e)
    conexao = False
else:
    conexao = True

margem = ' ' * 4

# Criação da nova tabela com ID
create_table_sql = """
CREATE TABLE colheitas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_colheita DATE,
    cultura VARCHAR2(100),
    quantidade NUMBER
)
"""
try:
    inst_cadastro.execute(create_table_sql)
    conn.commit()
    print("Tabela 'colheitas' criada com sucesso.\n")
except Exception as e:
    print("Erro ao criar tabela:", e)

# Loop principal do sistema
while conexao:
    os.system('cls' if os.name == 'nt' else 'clear')

    print("SISTEMA DE GESTÃO DE COLHEITAS")
    print("""
    1 - Registrar nova colheita
    2 - Gerar relatório completo
    3 - Excluir registro de colheita por ID
    4 - Excluir todos os registros
    5 - Sair
    """)

    escolha = input(margem + "Escolha -> ").strip()

    if not escolha.isdigit():
        print("Digite um número válido.")
        input("\nPressione ENTER para continuar...")
        continue

    escolha = int(escolha)

    os.system('cls' if os.name == 'nt' else 'clear')

    match escolha:
        case 1:
            print("----- REGISTRAR NOVA COLHEITA -----\n")

            try:
                cultura = input(margem + "Digite o produto da cultura: ")
                quantidade = float(input(margem + "Digite a quantidade colhida (em toneladas): "))
                data_colheita = input(margem + "Digite a data da colheita (dd/mm/aaaa): ")

                cadastro = f"""
                    INSERT INTO colheitas (cultura, quantidade, data_colheita)
                    VALUES ('{cultura}', {quantidade}, TO_DATE('{data_colheita}', 'DD/MM/YYYY'))
                """
                inst_cadastro.execute(cadastro)
                conn.commit()
                print("\n-- Colheita registrada com sucesso! --")

            except ValueError:
                print("Erro: Quantidade deve ser numérica!")
            except oracledb.Error as e:
                print("Erro na transação com o banco de dados.")
                print(e)

        case 2:
            print("----- RELATÓRIO DE COLHEITAS -----\n")
            try:
                inst_consulta.execute("SELECT id, cultura, quantidade, TO_CHAR(data_colheita, 'DD/MM/YYYY') FROM colheitas ORDER BY id")
                data = inst_consulta.fetchall()

                if not data:
                    print("Nenhuma colheita registrada!")
                else:
                    df = pd.DataFrame(data, columns=['ID', 'Cultura', 'Quantidade (t)', 'Data Colheita'])
                    print(df)

            except Exception as e:
                print("Erro ao gerar relatório:", e)

            input("\nPressione ENTER para continuar...")

        case 3:
            print("----- EXCLUIR REGISTRO DE COLHEITA -----\n")
            try:
                id_colheita = int(input(margem + "Digite o ID da colheita a excluir: "))
                inst_exclusao.execute("SELECT * FROM colheitas WHERE id = :1", [id_colheita])
                if not inst_exclusao.fetchone():
                    print("ID não encontrado!")
                else:
                    inst_exclusao.execute("DELETE FROM colheitas WHERE id = :1", [id_colheita])
                    conn.commit()
                    print("Colheita excluída com sucesso!")
            except ValueError:
                print("ID deve ser numérico!")
            except Exception as e:
                print("Erro na exclusão:", e)

            input("\nPressione ENTER para continuar...")

        case 4:
            print("----- EXCLUIR TODOS OS REGISTROS -----\n")
            try:
                inst_exclusao.execute("DELETE FROM colheitas")
                conn.commit()
                print("Todos os registros foram excluídos!")
            except Exception as e:
                print("Erro ao excluir todos os registros:", e)

            input("\nPressione ENTER para continuar...")

        case 5:
            conexao = False

        case _:
            print("Opção inválida. Escolha entre 1 e 5.")
            input("\nPressione ENTER para continuar...")

print("\nObrigado por utilizar o sistema de colheitas! :)")
